name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '8.0.x'
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './frontend'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
            
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              
          - name: 'Build frontend Image'
            run: |
              docker build . --tag ghcr.io/willvelida/frontend:latest
              docker push ghcr.io/willvelida/frontend:latest              
